function dydt = FreeTumble(t, x, I)
% Computes the derivative of angular velocity for free tumbling (no torques)
%x = [phi; theta; psi; wx; wy; wz]

%phi = yaw, theta=pitch, psi=roll
phi = x(1);
theta = x(2);
psi = x(3);

%angular velocities about x, y, z axes
wx = x(4);
wy = x(5);
wz = x(6);

%matrix of moments of inertia
Ixx = I(1);
Iyy = I(2);
Izz = I(3);

%--------------------------------------------------------------------------
%{
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\GAS\ADCSGITHUB\Simulations\Detumbling\TumbleAttitude\ZARYA_25544 Orbit Location and Magnetic Flux.csv
%
% Auto-generated by MATLAB on 10-Nov-2025 18:38:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_UTCG_", "Lat_deg_", "Lon_deg_", "Rad_km_", "x_Magnitude", "y_Magnitude", "z_Magnitude", "Magnitude_nT_", "DerivativeX", "DerivativeY", "DerivativeZ"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time_UTCG_", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Time_UTCG_", "EmptyFieldRule", "auto");

% Import the data
ZARYA_25544OrbitLocationAndMagneticFlux = readtable("C:\GAS\ADCSGITHUB\Simulations\Detumbling\TumbleAttitude\ZARYA_25544 Orbit Location and Magnetic Flux.csv", opts);

%% Clear temporary variables
clear opts

%-----DELETE IF BROKEN-----------------------------------------------------

%convert earth magnetic field into B vector
B = [ZARYA_25544OrbitLocationAndMagneticFlux.x_Magnitude, ...
     ZARYA_25544OrbitLocationAndMagneticFlux.y_Magnitude, ...
     ZARYA_25544OrbitLocationAndMagneticFlux.z_Magnitude];

%Define Permanent Magnet Magnetic Moment Vector
mPerm = [0.3, 0, 0];

%Calculate Torque based on Permanent magnet
T_Perm = cross(mPerm, B(t));
%}
%--------------------------------------------------------------------------

% 3-2-1 Euler Angle Kinematics (find a source to explain)
phi_dot = wx + wy * sin(phi) * tan(theta) + wz * cos(phi) * tan(theta);
theta_dot = wy * cos(phi) - wz * sin(phi);
psi_dot = (wy * sin(phi) + wz * cos(phi)) / cos(theta);

% Euler rotational equations (no torques)
wx_dot = ((T_Perm + (Iyy - Izz))/Ixx) * wy * wz;
wy_dot = ((T_Perm + (Izz - Ixx))/Iyy) * wz * wx;
wz_dot = ((T_Perm + (Ixx - Iyy))/Izz) * wx * wy;

%compute the euler rates and angular accalerations
dydt = [phi_dot; theta_dot; psi_dot; wx_dot; wy_dot; wz_dot];
end