%-------------------SUMMARY------------------------------------------------

%{

The purpose of this simulation is to simulate a tumbling 1U cubesat for 30
days starting on AUG 1 2026 00:00:00 based on initial angular velocities using the Newton-Euler rotational 
Equations of motion for rigid-bodies. 

INPUTS: ISS Longitude Latitude Altitude ORBIT DATA (from STK)(in ECEF reference frame),
IGRF Magnetic flux density data (From STK)(in ECEF reference frame), 
Moments of inertia of cubesat (IXX, IYY, IZZ), Initial Angular
Velocities (Wx, Wy, Wz), Initial Euler Angles (Phi, Theta, Psi).

Outputs: Euler angles over 30 days (Phi, Theta, Psi), Euler angle rates
over 30 days (PhiDot, ThetaDot, PsiDot), Angular Velocities in ECEF
Frame over 30 days

%}

%Pull Data from ISS orbit and magnetic field with IGRF field model and orbit
%from Aug 1 2026 - Aug 31 2026

%----------------Import LLA/IGRF Magnetic field information----------------

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename:
%    C:\GAS\ADCSGITHUB\CubeSat-Attitude-Damping-Simulation-With-Hysteresis-Rods-main\Simulations\Detumbling\PermanentMagnetTorque\GASRATS
%    Orbit Location and Magnetic Flux.csv
%
% Auto-generated by MATLAB on 10-Nov-2025 18:38:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_UTCG_", "Lat_deg_", "Lon_deg_", "Rad_km_", "x_Magnitude", "y_Magnitude", "z_Magnitude", "Magnitude_nT_", "DerivativeX", "DerivativeY", "DerivativeZ"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time_UTCG_", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Time_UTCG_", "EmptyFieldRule", "auto");

% Import the data
% FILEPATH MUST BE CHANGED BASED ON LOCATION OF ISS ORBIT AND MAGNEITC FIELD DATA
GASRATSOrbitLocationAndMagneticFlux = readtable("C:\GAS\ADCSGITHUB\Simulations\Detumbling\PermanentMagnetTorque\GASRATS Orbit Location and Magnetic Flux.csv", opts);

%% Clear temporary variables
clear opts

%--------------------Simulation Start--------------------------------------

%simulation conditions (start, end, timestep, length)
start_time = datetime(2026,8,1,0,0,0);
end_time = datetime(2026,8,2,0,0,0);

timestep = 1;
t_days = 1
t_full = 86400 * t_days
t_seconds = 0:timestep:t_full;

%%Cubesat Moments of Inertia (based on 1U cubesat) (kg*m^2)
Ixx = 0.02552;
Iyy = 0.02552;
Izz = 0.02552;

%Intertia column vector
I = [Ixx,Iyy,Izz];

%initial conditions for Attitude and Angular Velocity
%Initial Euler angles
phi0 = deg2rad(0);  %Yaw/z-axis
theta0 = deg2rad(0);  %Pitch/y-axis
psi0 = deg2rad(0);  %Roll/x-axis

%initial angular velocities about x, y, and z
wx0 = deg2rad(10);
wy0 = deg2rad(5);
wz0 = deg2rad(2);

%Inital State Vector 
state0 = [phi0; theta0; psi0; wx0; wy0; wz0];

%%%%%%%%%%%%%%%%%%%%%Permanent Magnet Torque Calculation%%%%%%%%%%%%%%%%%%%



%-----DELETE IF BROKEN-----------------------------------------------------

%convert earth magnetic field into B vector
B = [GASRATSOrbitLocationAndMagneticFlux.x_Magnitude, ...
     GASRATSOrbitLocationAndMagneticFlux.y_Magnitude, ...
     GASRATSOrbitLocationAndMagneticFlux.z_Magnitude];

%Define Permanent Magnet Magnetic Moment Vector
%mPerm = [0.3, 0, 0]; %In Body fixed frame


%Calculate Torque based on Permanent magnet
%T_Perm = cross(mP, B);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%ODE function call%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Choose settings for ODE45 solver 
%(UNDERSTAND DORMAND-PRINCE pair of RUNGE-KUTTA FORMULA)
%Set relative and absolute tolerance to 1e-8 because tight tolerances are
%needed for accuraccy. 
options = odeset('RelTol',1e-7,'AbsTol',1e-7);

%Run ODE45
[t,x] = ode45(@(t,x) FreeTumble(t,x,I), t_seconds, state0, options);

%extract Euler angles form ODE45
phi = x(:,1); %Yaw - z
theta = x(:,2); %Pitch - y
psi = x(:,3); %Roll - x

%extract angular velocities from ODE45
wx = x(:,4);
wy = x(:,5);
wz = x(:,6);

%convert Euler angles to degrees
phi_deg = rad2deg(phi);
theta_deg = rad2deg(theta);
psi_deg = rad2deg(psi);

%calculate 3-2-1Euler Rates (phidot,thetadot,psidot)
phi_dot   = wx + wy.*sin(phi).*tan(theta) + wz.*cos(phi).*tan(theta);
theta_dot = wy.*cos(phi) - wz.*sin(phi);
psi_dot   = (wy.*sin(phi) + wz.*cos(phi)) ./ cos(theta);

%convert Euler rates to degrees
phi_dot_deg = rad2deg(phi_dot);
theta_dot_deg = rad2deg(theta_dot);
psi_dot_deg = rad2deg(psi_dot);

%%%%%%%%%%%%%%%%%%%%%%% PLOTTING %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%plot Euler Angles 
figure;
plot(t,rad2deg(phi), 'LineWidth', 1.2); hold on;
plot(t,rad2deg(theta), 'LineWidth', 1.2); hold on;
plot(t,rad2deg(psi), 'LineWidth', 1.2); hold on;

xlabel('time(s)');
ylabel('Euler Angles (deg)');
legend ('\phi (roll)', '\theta (pitch)', '\psi(Yaw)')
title('3-2-1 Euler Angles - Free Tumble')

%plot Euler Angle Rates
figure;
plot(t, phi_dot_deg, 'LineWidth', 1.2); hold on;
plot(t, theta_dot_deg, 'LineWidth', 1.2); hold on;
plot(t, psi_dot_deg, 'LineWidth', 1.2); hold on;

xlabel('Time (s)');
ylabel('Euler Angle Rates (deg/s)');
legend('\phi_dot', '\theta_dot','\psi_dot');
title('3-2-1 Euler Angle Rates - Free Tumble');
grid on;

%Plot Angular Velocities
figure;
plot(t, rad2deg(wx), 'LineWidth',1.2); hold on;
plot(t, rad2deg(wy), 'LineWidth',1.2); hold on;
plot(t, rad2deg(wz), 'LineWidth',1.2); hold on;

xlabel('Time (s)');
ylabel('Angular Velocity (deg/s)');
legend('\omega_x', '\omega_y', '\omega_z');
title("Angular Velocities - Free Tumble - ODE45");
grid on;

%UNDERSTAND DIFFERENCE BETWEEN EULER ANGLE RATES AND ANGULAR VELOCITY

%--------------------------------------------------------------------------
% Extract Euler angles and Euler Angle Rates for attitude file in STK
%--------------------------------------------------------------------------

%number of attitude points = number of seconds
N = length(t);

% STK requires time offsets, not timestamps
timeOffsets = t;   % already 0:1:86400

%create .a file and open it to write
filename = 'GASRATSAttitude.a';
fid = fopen(filename, 'w');

%write header
fprintf(fid, 'stk.v.12.0\n\n');
fprintf(fid, '# WrittenBy    STK_v12.5.0\n\n');
fprintf(fid, 'BEGIN Attitude\n\n');
fprintf(fid, '  NumberOfAttitudePoints   %d\n\n', N);
fprintf(fid, '  ScenarioEpoch            1 Aug 2026 00:00:00.000000\n\n');
fprintf(fid, '  BlockingFactor           20\n\n'); %what does this do?
fprintf(fid, '  InterpolationOrder       1\n\n');
fprintf(fid, '  CentralBody              Earth\n\n');
fprintf(fid, '# Epoch in JDate format:  2461253.50000000000000\n');
fprintf(fid, '# Epoch in YYDDD format:	  26213.00000000000000\n\n\n');
fprintf(fid, '# Time of first point: 1 Aug 2026 00:00:00.000000000 UTCG = 2461253.50000000000000 JDate = 26213.00000000000000 YYDDD\n\n');
fprintf(fid, '  CoordinateAxes		 ICRF\n\n');
fprintf(fid, '  Sequence 321\n');
fprintf(fid, '  AttitudeTimeEulerAnglesAndRates\n');

%go through all timesteps "k" and write data into .a file
for k = 1:N
    fprintf(fid, '%.3f   %.6f   %.6f   %.6f   %.6f   %.6f   %.6f\n', ...
        timeOffsets(k), ...
        psi_deg(k), theta_deg(k), phi_deg(k), ...
        psi_dot_deg(k), theta_dot_deg(k), phi_dot_deg(k));
end

%write end of file text in .a file
fprintf(fid, 'EndAttitude\n');

%close file
fclose(fid);

%print command line statement confirming file was created
disp("Generated STK attitude file: " + filename);

%%%%%%%%%%%%%%%%%%%%%FREE TUMBLE FUNCTION%%%%%%%%%%%%%%%%%%%%%

function dydt = FreeTumble(t, x, I)
% Computes the derivative of angular velocity for free tumbling (no torques)
%x = [phi; theta; psi; wx; wy; wz]

%phi = yaw, theta = pitch, psi = roll
phi = x(1);
theta = x(2);
psi = x(3);

%angular velocities about x, y, z axes
wx = x(4);
wy = x(5);
wz = x(6);

%matrix of moments of inertia
Ixx = I(1);
Iyy = I(2);
Izz = I(3);

%---------------------CALCULATE Permanent Magnet Torque--------------------

% 3-2-1 Euler Angle Kinematics (find a source to explain)
phi_dot = wx + wy * sin(phi) * tan(theta) + wz * cos(phi) * tan(theta);
theta_dot = wy * cos(phi) - wz * sin(phi);
psi_dot = (wy * sin(phi) + wz * cos(phi)) / cos(theta);

% Euler rotational equations (no torques)
wx_dot = (((Iyy - Izz))/Ixx) * wy * wz;
wy_dot = (((Izz - Ixx))/Iyy) * wz * wx;
wz_dot = (((Ixx - Iyy))/Izz) * wx * wy;

%{
ANGULAR VELOCITY RATE CALCULATION WITH PERMANENT MAGNET TORQUE
wx_dot = ((T_Perm + (Iyy - Izz))/Ixx) * wy * wz;
wy_dot = ((T_Perm + (Izz - Ixx))/Iyy) * wz * wx;
wz_dot = ((T_Perm + (Ixx - Iyy))/Izz) * wx * wy;
%}

%compute the euler rates and angular accalerations
dydt = [phi_dot; theta_dot; psi_dot; wx_dot; wy_dot; wz_dot];
end