%{

QUESTIONS: Euler angle rates vs. Angular Velocities?, Body Fixed Frame vs
intertial Frame?

The purpose of this simulation is to simulate a tumbling 1.5U cubesat for 100
orbits starting on AUG 1 2026 00:00:00 based on initial angular velocities using the Newton-Euler rotational 
Equations of motion for rigid-bodies. 

INPUTS: ISS Longitude Latitude Altitude ORBIT DATA (from STK), WMM Magnetic flux density data
(From STK), Moments of inertia of cubesat (IXX, IYY, IZZ), Initial Angular
Velocities (Wx, Wy, Wz), Initial Euler Angles (Phi, Theta, Psi).

Outputs: Euler angles over 100 orbits (Phi, Theta, Psi), Euler angle rates
over 100 orbits (PhiDot, ThetaDot, PsiDot), Angular Velocities in ECEF
Frame over 100 orbits

%}

%Pull Data from ISS orbit and magnetic field with WMM field model and orbit
%from Aug 1 2026 - Aug 2 2026

%--------------------------------------------------------------------------

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\GAS\ADCSGITHUB\Simulations\Detumbling\TumbleAttitude\ZARYA_25544 Orbit Location and Magnetic Flux.csv
%
% Auto-generated by MATLAB on 10-Nov-2025 18:38:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time_UTCG_", "Lat_deg_", "Lon_deg_", "Rad_km_", "x_Magnitude", "y_Magnitude", "z_Magnitude", "Magnitude_nT_", "DerivativeX", "DerivativeY", "DerivativeZ"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time_UTCG_", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Time_UTCG_", "EmptyFieldRule", "auto");

% Import the data
ZARYA_25544OrbitLocationAndMagneticFlux = readtable("C:\GAS\ADCSGITHUB\Simulations\Detumbling\TumbleAttitude\ZARYA_25544 Orbit Location and Magnetic Flux.csv", opts);

%% Clear temporary variables
clear opts

%--------------------------------------------------------------------------

%simulation conditions (start, end, timestep, length)
start_time = datetime(2026,8,1,0,0,0);
end_time = datetime(2026,8,2,0,0,0);

timestep = 1;
t_seconds = 0:dt:86400;

%%Cubesat Moments of Inertia (kg*m^2)
Ixx = 0.02552;
Iyy = 0.02552;
Izz = 0.02552;
%Intertia column vector
I = [Ixx,Iyy,Izz];

%initial conditions for Attitude and Angular Velocity
%Initial Euler angles around x, y, and z
wx0 = deg2rad(10);
wy0 = deg2rad(5);
wz0 = deg2rad(2);
%Inital State Vector (LEARN EXACTLY WHAT A STATE VECTOR IS)
state0 = [wx0;wy0;wz0];
%Choose settings for ODE45 solver 

%set 1st step of angular velocity to initial condition
wx(1) = wx0;
wy(1) = wy0;
wz(1) = wz0;

%


